language: go

go:
  - 1.7
before_install:
 - sudo apt-get install python
 - sudo apt-get install -qq pkg-config fuse
 - sudo modprobe fuse
 - sudo chmod 666 /dev/fuse
 - sudo chown root:$USER /etc/fuse.conf
script:
  - go install github.com/tsileo/blobstash
  - go test -v ./...
  - python tests.py
